[package]
name = "cell_syntax"
version = "0.1.0"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"
license = "Zlib"

[dependencies]
cell_common = { path = "../cell_common" }
salsa = "0.15.2"
ordered-float = "2.0.0"
